### ISSUE TITLE
Findbugs support

### ISSUE THREAD

**Issue by ghost** [noveogroup/android-check#6] opened 2015-04-21 09:37 UTC
Hi there, do you have any plans to also include support for Findbugs?

**Comment by igelgrun** [comment] 2015-04-23 06:10
Hello,

Yes, it will be in one of the next releases.

**Comment by ghost** [comment] 2015-04-25 14:38
Mind if I ask for any ETA or Roadmap?

**Comment by igelgrun** [comment] 2015-04-27 13:35
Yes, it may be done in few days, but ...
The problem is to execute FindBugs task programmatically.

**Comment by jaredsburrows** [comment] 2015-07-04 03:12
+1

**Comment by aegis123** [comment] 2015-08-04 15:20
Any ETA on this?

**Comment by akhy** [comment] 2015-08-19 08:34
+1

**Comment by vbauer** [comment] 2015-08-19 08:38
:+1:

**Comment by igelgrun** [comment] 2015-09-24 07:07
FindBugs is now supported by new 1.2.0 version.

**Closed as completed by igelgrun** 2015-09-24 07:07 UTC
Labels: enhancement
