### ISSUE TITLE
Unable to exclude rules [UncommentedEmptyMethod]

### ISSUE THREAD

**Issue by ultraon** [noveogroup/android-check#17] opened 2015-11-13 09:57 UTC
Hello, i created project from scratch. Configured this plugin by default and after executing i'll get following error:

```
...
Executing findbugs FindBugsTask from ant task
:app:androidPmd FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:androidPmd'.
> java.lang.IllegalArgumentException: Unable to exclude rules [UncommentedEmptyMethod]; perhaps the rule name is mispelled?
...
BUILD FAILED
...
```

I use gradle 2.4, android gradle plugin 1.5.0.
Found related issue here http://sourceforge.net/p/pmd/bugs/1394/

**Comment by alxndrsn** [comment] 2016-04-14 16:02
+1: getting this with gradle 2.12; android-check 1.2.3; means that `androidPmd` won't run

**Comment by alxndrsn** [comment] 2016-04-14 16:05
This is a duplicate of #13

**Comment by smalichenko** [comment] 2017-04-11 04:34
Fixed & released.

**Closed as completed by smalichenko** 2017-04-11 04:34 UTC
